name: Docker Build, Tag, and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-tag-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shabd56
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-temp-image1 .

      - name: Tag image with Docker Hub repo name
        run: |
          docker tag my-temp-image1 shabd56/my-image-name:v1

      - name: Push image to Docker Hub
        run: |
          docker push shabd56/my-image-name:latest
